//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.23 at 05:21:56 PM CEST 
//


package com.thalesgroup.optet.devenv.jaxb.optetprofiles;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="optetProfile" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="checkstyle">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="pathconf" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="used" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="codepro">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="profile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="used" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="pmd">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="used" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="ruleset" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="findbugs">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="used" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="ruleset" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "optetProfile"
})
@XmlRootElement(name = "optetProfiles")
public class OptetProfiles {

    protected List<OptetProfiles.OptetProfile> optetProfile;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the optetProfile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optetProfile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptetProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OptetProfiles.OptetProfile }
     * 
     * 
     */
    public List<OptetProfiles.OptetProfile> getOptetProfile() {
        if (optetProfile == null) {
            optetProfile = new ArrayList<OptetProfiles.OptetProfile>();
        }
        return this.optetProfile;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="checkstyle">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="pathconf" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="used" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="codepro">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="profile" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="used" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="pmd">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="used" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="ruleset" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="findbugs">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="used" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="ruleset" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "checkstyle",
        "codepro",
        "pmd",
        "findbugs"
    })
    public static class OptetProfile {

        @XmlElement(required = true)
        protected OptetProfiles.OptetProfile.Checkstyle checkstyle;
        @XmlElement(required = true)
        protected OptetProfiles.OptetProfile.Codepro codepro;
        @XmlElement(required = true)
        protected OptetProfiles.OptetProfile.Pmd pmd;
        @XmlElement(required = true)
        protected OptetProfiles.OptetProfile.Findbugs findbugs;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "editable")
        protected Boolean editable;
        @XmlAttribute(name = "default")
        protected Boolean _default;
        @XmlAttribute(name = "description")
        protected String description;

        /**
         * Gets the value of the checkstyle property.
         * 
         * @return
         *     possible object is
         *     {@link OptetProfiles.OptetProfile.Checkstyle }
         *     
         */
        public OptetProfiles.OptetProfile.Checkstyle getCheckstyle() {
            return checkstyle;
        }

        /**
         * Sets the value of the checkstyle property.
         * 
         * @param value
         *     allowed object is
         *     {@link OptetProfiles.OptetProfile.Checkstyle }
         *     
         */
        public void setCheckstyle(OptetProfiles.OptetProfile.Checkstyle value) {
            this.checkstyle = value;
        }

        /**
         * Gets the value of the codepro property.
         * 
         * @return
         *     possible object is
         *     {@link OptetProfiles.OptetProfile.Codepro }
         *     
         */
        public OptetProfiles.OptetProfile.Codepro getCodepro() {
            return codepro;
        }

        /**
         * Sets the value of the codepro property.
         * 
         * @param value
         *     allowed object is
         *     {@link OptetProfiles.OptetProfile.Codepro }
         *     
         */
        public void setCodepro(OptetProfiles.OptetProfile.Codepro value) {
            this.codepro = value;
        }

        /**
         * Gets the value of the pmd property.
         * 
         * @return
         *     possible object is
         *     {@link OptetProfiles.OptetProfile.Pmd }
         *     
         */
        public OptetProfiles.OptetProfile.Pmd getPmd() {
            return pmd;
        }

        /**
         * Sets the value of the pmd property.
         * 
         * @param value
         *     allowed object is
         *     {@link OptetProfiles.OptetProfile.Pmd }
         *     
         */
        public void setPmd(OptetProfiles.OptetProfile.Pmd value) {
            this.pmd = value;
        }

        /**
         * Gets the value of the findbugs property.
         * 
         * @return
         *     possible object is
         *     {@link OptetProfiles.OptetProfile.Findbugs }
         *     
         */
        public OptetProfiles.OptetProfile.Findbugs getFindbugs() {
            return findbugs;
        }

        /**
         * Sets the value of the findbugs property.
         * 
         * @param value
         *     allowed object is
         *     {@link OptetProfiles.OptetProfile.Findbugs }
         *     
         */
        public void setFindbugs(OptetProfiles.OptetProfile.Findbugs value) {
            this.findbugs = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the editable property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isEditable() {
            return editable;
        }

        /**
         * Sets the value of the editable property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setEditable(Boolean value) {
            this.editable = value;
        }

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setDefault(Boolean value) {
            this._default = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="pathconf" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="used" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Checkstyle {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "pathconf")
            protected String pathconf;
            @XmlAttribute(name = "used")
            protected Boolean used;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the pathconf property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPathconf() {
                return pathconf;
            }

            /**
             * Sets the value of the pathconf property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPathconf(String value) {
                this.pathconf = value;
            }

            /**
             * Gets the value of the used property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isUsed() {
                return used;
            }

            /**
             * Sets the value of the used property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setUsed(Boolean value) {
                this.used = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="profile" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="used" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Codepro {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "profile")
            protected String profile;
            @XmlAttribute(name = "used")
            protected Boolean used;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the profile property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProfile() {
                return profile;
            }

            /**
             * Sets the value of the profile property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProfile(String value) {
                this.profile = value;
            }

            /**
             * Gets the value of the used property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isUsed() {
                return used;
            }

            /**
             * Sets the value of the used property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setUsed(Boolean value) {
                this.used = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="used" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="ruleset" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Findbugs {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "used")
            protected Boolean used;
            @XmlAttribute(name = "ruleset")
            protected String ruleset;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the used property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isUsed() {
                return used;
            }

            /**
             * Sets the value of the used property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setUsed(Boolean value) {
                this.used = value;
            }

            /**
             * Gets the value of the ruleset property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRuleset() {
                return ruleset;
            }

            /**
             * Sets the value of the ruleset property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRuleset(String value) {
                this.ruleset = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="used" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="ruleset" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Pmd {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "used")
            protected Boolean used;
            @XmlAttribute(name = "ruleset")
            protected String ruleset;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the used property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isUsed() {
                return used;
            }

            /**
             * Sets the value of the used property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setUsed(Boolean value) {
                this.used = value;
            }

            /**
             * Gets the value of the ruleset property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRuleset() {
                return ruleset;
            }

            /**
             * Sets the value of the ruleset property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRuleset(String value) {
                this.ruleset = value;
            }

        }

    }

}
